src/html.js
src/identity.js
src/index.js
src/md.js
src/svg.js
src/template.js
test/index-test.js

Structured HTML templates!

---

src/tex.js

Use String.raw for tex.

---

src/html.js

... as discussed in person and in: https://github.com/observablehq/notebook-stdlib/pull/18

Fixes #17, #18, Allow Safari to work with template elements via importNode()

---

.eslintrc.json
package.json
rollup.config.js
src/library.js
yarn.lock

This simplifies overriding the stdlib slightly.
This PR also updates our dependencies. The commits are separate if you’d prefer to review those changes independently.
Ref. https://talk.observablehq.com/t/embedded-width/1063/6

Make library properties writable.

---

src/tex.js

Ref. https://talk.observablehq.com/t/defining-latex-macros/1310/3

Expose tex.options.

---

src/md.js

Restore implicit div wrapping for md.

---

package.json
yarn.lock

chore(package): update husky to version 3.0.2

---

src/tex.js

Upgrade KaTeX to 0.11.

---

src/generators/input.js

For multiple select, expose an array of values.

---

src/fileAttachment.js
test/fileAttachments-test.js

```js
FileAttachment("foo.txt") instanceof FileAttachment // is now true
```

Fix instanceof FileAttachment.

---

README.md
src/fileAttachment.js

As described here: https://observablehq.com/d/8f9d08fe2416fc3f

Add CSV and TSV parsing.

---

src/library.js
test/index-test.js

Oops, I missed this one before, but it’s super useful!
https://observablehq.com/@observablehq/graphviz

Add @observablehq/graphviz

---

README.md

length minus one

---

bin/resolve-dependencies
src/dependencies.js
src/library.js
test/index-test.js

Recommend topojson-client

---

src/dependencies.js

https://github.com/observablehq/plot/releases

@observablehq/plot 0.2.5

---

src/dependencies.js

Sigh. Quick followup for a bug in diverging scales…

@observablehq/plot 0.2.7

---

src/dependencies.js
src/fileAttachment.js
src/index.js
src/library.js

Depends on https://github.com/observablehq/inputs/pull/188.

@observablehq/inputs 0.10.1

---

src/dependencies.js

| library | old version | new version | release notes |
|--|--|--|--|
| @observablehq/inputs | 0.10.1 | 0.10.2 | https://github.com/observablehq/inputs/releases |
| d3 | 7.1.0 | 7.1.1 | https://github.com/d3/d3/releases |
| sql.js | 1.6.1 | 1.6.2 | https://github.com/sql-js/sql.js/compare/v1.6.1...v1.6.2 |

update recommended libraries

---

src/table.mjs
test/table-test.mjs

Per https://github.com/observablehq/stdlib/pull/304#pullrequestreview-1138285412

tweaks to __table

---

src/duckdb.js

We want a dialect here so we know when we’re using DuckDB.

duckdb dialect

---

src/table.js

Works with [#8953](https://github.com/observablehq/observablehq/pull/8953) in observablehq
This is a small change to instantiate a DuckDBClient for Arrow tables, but it comes with a lot of questions:
- will it cause side effects to instantiate here?
- will we be instantiating a DuckDBClient too often?
- how expensive is it to instantiate one?
- is it possible to do it in a way that persists, instead?
Demo:

Instantiate DuckDBClient for Arrow tables

---

src/table.js
test/table-test.js

Resolves #347 (see issue for details).

Add validity check for integers

---

src/dependencies.js

https://github.com/observablehq/plot/releases
https://github.com/d3/d3/releases

d3 7.8.4, @observablehq/plot 0.6.5

---

src/dependencies.js

https://github.com/observablehq/plot/releases/tag/v0.6.6

Observable Plot 0.6.6

---

src/dependencies.js

Depends on https://github.com/observablehq/plot/releases/tag/v0.6.8.

@observablehq/plot 0.6.8

---

package.json
src/dependencies.js

Depends on https://github.com/observablehq/plot/pull/1727.

@observablehq/plot 0.6.9

---

src/dependencies.js

ref: https://github.com/observablehq/feedback/issues/588

Upgrade duckdb-wasm to 1.27.0

---

package.json
src/dependencies.js

Depends on https://github.com/observablehq/plot/pull/1854.

@observablehq/plot 0.6.11

---

package.json
src/dependencies.js

Upgrades:
* Observable Plot ([0.6.16](https://github.com/observablehq/plot/releases/tag/v0.6.16))
* Observable Inputs ([0.11.0](https://github.com/observablehq/inputs/releases/tag/v0.11.0))
Skipping other potential upgrades:
```diff
--- a/src/dependencies.js
+++ b/src/dependencies.js
@@ -9,16 +9,16 @@ export const lodash = dependency("lodash", "4.17.21", "lodash.min.js");
export const htl = dependency("htl", "0.3.1", "dist/htl.min.js");
export const jszip = dependency("jszip", "3.10.1", "dist/jszip.min.js");
export const marked = dependency("marked", "0.3.12", "marked.min.js");
-export const sql = dependency("sql.js", "1.8.0", "dist/sql-wasm.js");
-export const vega = dependency("vega", "5.22.1", "build/vega.min.js");
-export const vegalite = dependency("vega-lite", "5.6.0", …
```

v5.8.8: upgrade Plot (0.6.16) and Inputs (0.11.0)
