- src/html.js
- src/md.js
- src/svg.js
- src/template.js
Unlike elements, document fragments “dissolve” when they are added to the DOM. Their self-destructive nature makes them difficult to use as stable representations of a fragment of a document; for example, you can add event listeners to a document fragment, but when the document fragment is attached to the DOM, the fragment empties and so the event listeners will never fire.
This restores the previous behavior of the html tagged template literal: if the template literal results in multiple top-level nodes, these nodes are wrapped in an implicit DIV. Likewise, the svg tagged template literal uses an implicit G.
> Don’t generate document fragments.

- README.md
- src/generators/disposable.js
- src/generators/observe.js
- src/generators/queue.js
- src/noop.js
- test/generators/disposable-test.js
If *iterator*.return doesn’t return an object, then for-of crashes.
> Fix crash in for-of.

- package.json
- rollup.config.js
- yarn.lock
* Creates UMD and ES Module bundles of the standard library.
> Notebook Downloads (Standard Library Changes)

- src/tex.js
Rather than overriding the styles in the UI, patch the KaTeX distribution to include our preferred styles directly. For the patched distribution, see:
https://github.com/observablehq/katex
> Tweak Katex styles.

- README.md
- rollup.config.js
- src/library.js
- src/require.js
For example, to declare React’s missing UMD entry:
```js
react = require.alias({
react: "react/umd/react.production.min.js"
})("react")
```
You can also use this to pin exact versions.
> Add require.alias.

- src/md.js
This will require an upstream PR to notebook-runtime. I've tested notebook-runtime to confirm that that'll be seamless.
The gist is that, for tutorials and similar content, we'll want `viewof` and `mutable` to highlighted keywords. Right now they're unrecognized by highlight.js.
> Update highlight dependency to highlight Observable keywords and builtins

- src/md.js
Upstream, I want to help out mobile / smallscreen users by allowing code blocks to scroll horizontally. Right now any wide code block on a mobile phone is simply cut off.
But I want to do this in a way that's unlikely to break existing notebooks - for example, if someone is using a `pre` element in the output from a `html` tagged template. So this change attaches a class name to the `pre` element in Markdown output only.
> Differentiate marked-generated pre elements by adding a class to them.

- src/dom/download.js
Fixes #75.
* Allows the *value* to be specified optionally as a promise, a function, or a function that returns a promise. If a promise or a function that returns a promise, the first click changes the label to “Saving…” and disables the button while waiting for the promise to resolve, then changes the label to “Download”, and the second click will do the download.
* If the *value* is specified as a function, it is re-evaluated on each click.
* Changes the default label to “Save” instead of “Download” (for better compatibility with asynchronous values, where the “Saving…” and “Download” labels are applied internally and not customizable).
> Lazy DOM.download.

- package.json
- rollup.config.js
- src/md.js
- yarn.lock
One part of https://github.com/observablehq/notebook/issues/2197
Main gotcha that happens here is that the dependency path notebook - runtime - stdlib ends up with the 'module' entry in stdlib, and that means that it tries to import marked, and because marked is commonjs, it fails. So… we may need to either special-case that in the notebook, or something else.
> Embed marked

- .gitignore
- package.json
- test/generators/disposable-test.js
- test/index-test.js
- test/promises/delay-test.js
- yarn.lock
Switching more of our components to tap. Gives us code coverage, cuts dependency bloat (obviates observablehq/tape, tape-await, tap-junit, and esm), and gives us more readable reporters.
> Switch to tap

- src/fileAttachment.js
Currently, calling `.image()` on a FileAttachment will fail if the attachment’s ".url()" returns a relative path.
> File attachments image() "invalid URL" fix

- README.md
- package.json
- src/dom/uid.js
- src/fileAttachment.js
- src/index.js
- src/library.js
- test/index-test.js
- yarn.lock
... for use in UI, API (for downloads), and embeds.
- UI: resolve() function posts messages up to the parent frame to get signed URLs for private files.
- API: resolve() function is compiled with relative paths to downloaded files in the folder hierarchy.
- Embeds: resolve() function is compiled into the ES Modules, with absolute URLs of published files.
---
- Embeds: resolve() function is compiled into the generated ES Modules, with a map from name to absolute public (CloudFront), or private (currently CloudFront, future API) URLs.
- Downloads: resolve() function is compiled into the generated ES Modules, with a map from name to relative path on disk.
- Imports: Identical to Embeds, compiled with absolute URLs.
- UI: Passes in a `resolve()` function to this implementation that is capable …
> FileAttachments: Stdlib Implementation

- src/generators/disposable.js
- src/generators/observe.js
- src/generators/queue.js
Fixes #89.
My initial inclination was to just log a warning, but since warnings are only visible if you open the developer console, I figured that wouldn’t actually help people recognize the mistake.
> Error on invalid dispose function.

- package.json
- src/fileAttachment.js
- test/fileAttachments-test.js
Ref: https://github.com/observablehq/notebook/issues/5002
Previously: https://github.com/observablehq/compiler/pull/24
(Private issues)
If a FileAttachment object is created with a `URL` object, ensure that it is coerced to a string.
> File attachment URL strings (3.3.2)

- .github/workflows/nodejs.yml
- src/constant.js
- src/library.js
- src/promises/when.js
- src/vegalite.js
- test/index-test.js
This adds a handful of first-party and sanctioned third-party libraries to the Observable standard library for convenient access from notebooks. This set of libraries may grow over time based on demand. The current set is:
* `d3` - [D3.js](https://d3js.org)
* `htl` - Observable’s [Hypertext Literal](https://github.com/observablehq/htl)
* `Inputs` - [Observable Inputs](https://github.com/observablehq/inputs)
* `Plot` - [Observable Plot](https://github.com/observablehq/plot)
* `_` - [Lodash](https://lodash.com)
* `vl` - [Vega-Lite API](https://vega.github.io/vega-lite-api/)
In the last case, some additional code is required based on [this notebook](https://observablehq.com/@vega/vega-lite-api).
The trickiest part here is version pinning. I chose to hard-code the versions and paths in the …
> Add recommended libraries

- src/library.js
- test/generators/generators-test.js
> Expose Generators as constant

- src/fileAttachment.js
- src/zip.js
Adds *fileAttachment*.zip which returns a promise to a ZipArchive. The ZipArchive exposes an *archive*.fileNames() method which returns the array of file names, and an *archive*.file(*name*) method which returns a FileAttachment-like object. So, to load a CSV file in a ZIP file, you can now say:
```js
archive = FileAttachment("ACS_14_5YR_B01003.zip").zip()
```
```js
data = archive.file("ACS_14_5YR_B01003_with_ann.csv").csv({typed: true})
```
As with XLSX #215, I’ve decided not to expose JSZip as a recommended library, and instead wrap it with a more minimal abstraction that feels more Observable-ish.
> Add support for ZIP file attachments.

- rollup.config.js
- src/fileAttachment.js
- src/library.js
- src/sqlite.js
- test/index-test.js
> Expose SQLiteDatabaseClient

- bin/resolve-dependencies
- package.json
- src/dependencies.js
- src/dependency.js
- src/fileAttachment.js
- src/library.js
- src/md.js
- src/sqlite.js
- src/tex.js
- src/vegalite.js
- yarn.lock
I wanted to make it easier to keep these versions up-to-date, and to avoid hard-coding the versions in multiple places. I couldn’t figure out a good way to track the versions using yarn (I considered devDependencies), but this at least gives us a script we can run to refresh the dependency versions and then see if we want to update.
> Automate version resolution

- bin/resolve-dependencies
- src/dependencies.js
- src/fileAttachment.js
- src/library.js
- test/index-test.js
Apache Arrow is exposed as `Arrow` in the standard library, and _fileAttachment_.arrow() returns a Promise to an Arrow.Table.
> Add Apache Arrow as a recommended library and supported file attachment

- bin/resolve-dependencies
- src/dependencies.js
- src/fileAttachment.js
- src/zip.js
I missed this when rebasing #222. This also upgrades JSZip from 3.6.0 to 3.7.0 which you can see here:
https://github.com/Stuk/jszip/compare/v3.6.0...e5b3f0ddaa8182cd6ea253e97f678b9f36d0d8ac
The only change appears to be a security fix for weirdly-named files which I do not think applies in our usage.
> resolve jszip

- package.json
- src/xlsx.js
- test/xlsx-test.js
- yarn.lock
Is ExcelJS as a devDependency ok? There was a previous risk in using a `mockWorkbook` function in tests previously and this guarantees better compatibility. But it's a whole new library to bring in.
> Prefer public ExcelJS APIs

- src/dependencies.js
Includes https://github.com/observablehq/inputs/pull/169, which isn't required anymore for #248, but nice to have.
> Update Inputs to 0.9.2.

- package.json
- yarn.lock
We have GitHub Actions CI now, so I don’t see a need to keep this around.
Note that husky will not automatically uninstall itself if you use yarn. ☹️ Assuming you don’t have any other git hooks defined locally, you can remove the remains of husky like so:
```
rm .git/hooks/*
git init
```
> remove husky

- README.md
- src/fileAttachment.js
This allows the *resolve* function used with FileAttachments to return a `mimeType` in addition to a `url`, and if so, the MIME type will be exposed on the resulting file attachment.
> mimeType for FileAttachment

- bin/resolve-dependencies
- src/dependencies.js
- src/leaflet.js
- src/library.js
- test/index-test.js
Adds [Leaflet](https://leafletjs.com/) to the list of recommended libraries (so that it’s easier for us to make a snippet for creating Leaflet maps).
> add leaflet to recommended libraries

- src/sqlite.js
Partially addresses https://github.com/observablehq/observablehq/issues/6557 and https://github.com/observablehq/observablehq/issues/5368
Along with https://github.com/observablehq/stdlib/pull/283, this PR will make SQLiteDatabaseClient work with the Table cell.
> SQLiteDatabaseClient.queryTag

- src/sqlite.js
This implements the **describeTables** and **describeColumns** methods for SQLite.
Fixes #288.
> SQLiteDatabaseClient schema methods

- README.md
- src/dependency.js
- src/fileAttachment.js
- src/library.js
- src/require.js
- src/sqlite.js
- yarn.lock
This PR allows the user to change the require implementation by assigning to Library.require.
Originally, I intended this to be local to the Library instance (hence the _resolve_ argument to the Library constructor). However, there are a number of places where we want to require stuff statically, such as within the AbstractFile class definition. Therefore it seems unavoidable to have only a single definition of require. (Eventually we want to move everything to dynamic ES module imports anyway…)
> allow Library.require override

- src/sqlite.js
Per https://sqlite.org/lang_attach.html
> The schema-names 'main' and 'temp' refer to the main database and the database used for temporary tables. The main and temp databases cannot be attached or detached. … If the name of the table is unique across all attached databases and the main and temp databases, then the schema-name prefix is not required. If two or more tables in different databases have the same name and the schema-name prefix is not used on a table reference, then the table chosen is the one in the database that was least recently attached.
> treat main as the default schema

- src/py.js
> patch matplotlib’s show

- src/index.mjs
- src/library.mjs
- src/table.mjs
- test/index-test.mjs
- test/table-test.mjs
This PR moves the __query function and its dependencies out of the Next worker code and into stdlib. I also moved a set of tests over for the query template function (which I renamed to `makeQueryTemplate`, which I find a bit clearer). 
Once we upgrade stdlib in Classic, this will serve as a partial fix for Data Table embeds (embeds will show the array of results, but not the full table UI).
> Move __query and its dependencies to stdlib

- package.json
- src/index.mjs
- src/table.mjs
- test/table-test.mjs
- yarn.lock
This PR ports over @mbostock's `__table` function, as defined in https://github.com/observablehq/observablehq/pull/8300, and adds missing support for the `lt` and `gt` filter operations. Also adds unit tests.
> Add __table function and unit tests

- src/index.mjs
- src/table.mjs
Adds support file FileAttachment data sources to SQL and data table cells.
> loadDataSource

- src/index.js
Exports the `__table` function for use in the Observable Data Table and SQL cells.
> Export __table function

- src/arrow.js
- src/duckdb.js
- src/table.js
- test/table-test.js
This…
* Adopts DuckDB for CSV, TSV, JSON, Arrow and Parquet file sources for SQL cells
* Adopts DuckDB for Arrow and Parquet file sources for data table cells
* Adopts DuckDB for Arrow table sources for data table cells
* Fixes a bug with DuckDBClient.describeColumns when the table name needs escaping
🦆🦆🦆
> use DuckDB for more data sources

- src/duckdb.js
Rather than hard-coding CSV = comma and TSV = tab (despite the name), use DuckDB’s magical automatic delimiter inference by default. You can still specify a delimiter explicitly if you use the _delimiter_ option.
Ref. https://observablehq.com/d/f11bdd2a9af411c5
> use DuckDB’s auto delimiter by default

- src/table.js
Resolves https://github.com/observablehq/observablehq/issues/9381
I did see the other possible solution suggestion, to bypass the cache entirely for array sources that are not done. If that seems like a better solution, happy to revise.
> Update caching logic for tables

- src/sqlite.js
Resolves #333
- Adds `ORDER BY schema, name` to `describeTables`
Before|After
-|-
> Fix sort order for SQLite tables

- src/duckdb.js
- src/index.js
- src/table.js
Resolves #330 
- Identifies Arquero tables by presence of a `toArrow` function
- Uses Arrow's `.tableFromIPC()` with Arquero's `.toArrowBuffer()` as source for a new DuckDBClient
> Support Arquero tables

- src/arquero.js
- src/duckdb.js
- src/index.js
- src/table.js
As we are currently discussing
> Move isArqueroTable to fix circular dependency

- src/table.js
- test/table-test.js
This fixes a bug where `v` and `nv` filters don't work for SQL data sources 😬 The issue is that, because we handle those filters in the binary operation conditional block, we append the primitive value (which contains the expected type) to the SQL query https://github.com/observablehq/stdlib/blob/main/src/table.js#L420. You end up with a query with broken syntax in the `WHERE` clause:
We should just consider `v` and `nv` to be unary operations (I think it was originally my suggestion to handle them in the binary op block so that's my bad!!). I also added a unit test for this case.
> Fix v and nv filters in SQL

- src/duckdb.js
- src/table.js
Partially resolves https://github.com/observablehq/observablehq/issues/9857 
The two cases it resolves are:
1. @Fil's case with thousands of rows of "F", which DuckDB interpreted as boolean, then threw an error when it encountered an "M."  
2. Allison's case of ejecting to SQL and it silently failing due to a type mismatch.
Case 2 (and likely case 1) occurred when the mismatch was found in a row > 10240, as that's the (default?) sample size DuckDB checks when inferring types. 
Now, if `insertCSVFromPath` fails, we catch it, check whether it failed due to a conversion error, and if so, try again with all columns as strings. Only CSV and TSV files are affected by this change. 
The error for case 1 (before): 
Case 1 fixed (after):  
Video showing before and after for case 2: …
> DuckDB to import columns as strings as a fallback

- src/table.js
- test/table-test.js
Implement column renaming in stdlib. Specifically, we now set column name overrides based on the `names` property in `node.data.operations`, which is added in [this PR](https://github.com/observablehq/observablehq/pull/10009).
For SQL data sources, we do this by modifying the `SELECT` clause. For in-memory data sources, we create a copy of the source data and modify it to use the new names.
> Handle column renaming in makeQueryTemplate and __table

- src/index.js
- src/table.js
- test/table-test.js
Resolves https://github.com/observablehq/observablehq/issues/9862 and https://github.com/observablehq/observablehq/issues/9673
In this inference approach, we take a sample (currently the first 100 rows), and for each column, count how many times we encounter each possible data type. Then, if > 90% of the sampled values conform to that type, we take the most frequently encountered type as the column's type. If not, we use type "other."
These changes include some support for upcoming [column type assertions](https://github.com/observablehq/observablehq/pull/10133), but for the purposes of this PR, I'm testing against main. 
https://user-images.githubusercontent.com/111310561/214719295-8326f325-879b-4b8a-9d9f-2397b28951de.mov
> Infer schemas and coerce data for table cells

- src/table.js
This PR renames the key `.type` to `.types` on the incoming `operations` argument for compatibility with the data structure on Observablehq.
> Rename type to types

- src/table.js
An attempt to address the problem of slow cells downstream of streaming data sources (laid out in https://github.com/observablehq/observablehq/issues/10193).
With fast database clients, I saw a bit of a noticeable difference in streaming speed, but I don't feel like it's enough to be a problem.
https://user-images.githubusercontent.com/6464196/218569409-ae621b88-cb8e-45c9-9d9d-016601fbfb84.mov
https://user-images.githubusercontent.com/6464196/218569436-c06006ad-9284-4bc4-b53d-0ee8fe07cc23.mov
> Increase accumulateQuery debounce to 150ms

- src/table.js
This resolves an error where chart cells were fetching the table schema for a CSV, TSV, JSON, or SQLite file and receiving no columns back.
> Load tabular data files for chart cells

- src/dependencies.js
- src/duckdb.js
> @duckdb/duckdb-wasm 1.24

- src/index.js
Supports [this fix](https://github.com/observablehq/observablehq/pull/10916), which makes schema inference consistent across stdlib and the monorepo.
> Export inferSchema

- bin/resolve-dependencies.js
- src/arrow.js
- src/dependencies.js
- src/fileAttachment.js
duckdb-wasm@1.24 depends on arrow11 (after https://github.com/duckdb/duckdb-wasm/commit/18dd6c7096fe888dbdfb7e9a1cdd559560d53c97); because of this, with #356 loadDataSource does not create tables from arrays any more.
In this tentative PR I add full support for arrow11 on top of the existing arrow9 and arrow4. It might be enough to support arrow11 only in the case of duckdb, but supporting it as a filetype felt the right thing to do. (Not tested though.)
DEMO: https://observablehq.com/@observablehq/duckdb-1-24-breaks-insertion-in-sql-mode
Here's a unit test I wanted to add, unfortunately it fails because loadArrow() wants an http-resource.
```diff
--- a/test/query-test.js
+++ b/test/query-test.js
@@ -1,5 +1,5 @@
import assert from "assert";
-import {__query} from "../src/table.js"; …
```
> duckdb-wasm@1.24 depends on arrow11

- README.md
- src/fileAttachment.js
- src/table.js
- test/fileAttachments-test.js
- test/table-test.js
Since 2020, file.csv and file.tsv have allowed you to pass {typed: true} to apply d3.autoType, which looks line by line and tries to guess the types. More recently, the data table cell has introduced an internal [inferSchema function](https://github.com/observablehq/stdlib/blob/89f27007453ea1919493dca3fb94b7a5bde03222/src/table.js#L835-L885), which instead looks at a sample of rows and picks the most frequent type.
This introduces a new {typed: "auto"} option, which calls inferSchema and then coerces all rows to that schema, allowing FileAttachment calls to match the behavior of the data table cell. It also uses that new "auto" option in loadChartDataSource.
This duplicates a couple lines of the __table function…
https://github.com/observablehq/stdlib/blob/89f27007453ea1919493dca3fb94b7a5b …
> Add file.csv({typed: "auto"}) option that uses inferSchema

- src/index.js
- src/table.js
- test/table-test.js
This PR adds a `getSchema` function, building on a [suggestion from Mike](https://github.com/observablehq/observablehq/pull/11496#discussion_r1165998001). This function conditionally infers a schema depending on whether or not a valid one exists on the source, combines the schema with any saved type assertions, and determines whether or not the source data needs to be coerced.
We will use `getSchema` in both `__table` and in the table schema tasks in the worker (I'll update https://github.com/observablehq/observablehq/pull/11496 to use this function), and thereby unify the two paths that we currently have for type inference.
I also added a missing unit test for type assertion in `__table`, as well as some tests for `getSchema`.
> Add and export getSchema function

- src/table.js
- test/table-test.js
(Based on a suggestion [from Mike](https://github.com/observablehq/stdlib/pull/363#discussion_r1167258471))
Remove .columns from `__table`. It's no longer needed since we always guarantee that we'll return a .schema, and .schema is a superset of the information in .columns.
One thing I'm not too sure about – if the source has a .columns property and the source isn't modified in `__table`, the .columns property will pass through and remain in the output. Is that ok, or do we need to standardize `__table` by making sure .schema is the only property on the output?
> Remove .columns

- src/table.js
- test/table-test.js
Part of https://github.com/observablehq/observablehq/issues/11623
This PR adds support for derived columns in the `__table` function. In this first version, we won't support derived columns for database sources.
Notable changes:
- Pulled the logic for inferring types and coercing rows into a separate `applyTypes` function. We now run this twice, first on the source dataset, and second on the derived dataset, before merging the two. Type inference/coercion must be done separately on the derived dataset because it may depend on values in the source dataset already being coerced.
- Added a `.fullSchema` property to the return value of `__table`. This property contains the schema information for _all_ columns in the dataset, regardless of whether or not they are selected (`.schema` only …
> Derived columns

- src/table.js
Accompanying compiler PR: https://github.com/observablehq/compiler/pull/87
Partially addresses https://github.com/observablehq/observablehq/issues/11974
Some context: during a recent column derivation bug bash, there was confusion about the `index` and `rows` properties in the derive formula because they represent the index and rows values from the original data source, not the index and rows as seen in the table display. This is the case because column derivations are computed before any filters, sorts, or other operations are applied, since those operations may reference derived columns. The decision was made to remove these arguments in order to avoid potential confusion – if we get user feedback requesting access to these values, we can figure out how to add them back in a way that …
> Remove index and rows as arguments to the derive expression

- package.json
- src/dependencies.js
- Reverts https://github.com/observablehq/stdlib/commit/b012a76706e7bd94e3ead92d4cd637580a237d68
- [Inputs v0.10.6](https://github.com/observablehq/inputs/releases/tag/v0.10.6)
- [Plot v0.6.10](https://github.com/observablehq/plot/releases/tag/v0.6.10)
I can break the dependencies changes and the version bump into separate PRs if you’d prefer.
> 5.8.1: downgrade DuckDB; upgrade Plot and Inputs

- src/library.js
- test/index-test.js
- Adds shortened pizza paradise sample as `pizza` (verified unclaimed) to stdlib datasets. Already uploaded static file)
- Fixes "Sample datasets" link comment
---
- Works on internal # 13706
- Follows https://github.com/observablehq/stdlib/pull/284
Docs:
- https://observablehq.com/@observablehq/sample-datasets
- https://observablehq.com/@observablehq/pizza-paradise-data
> feat: add pizza paradise sample dataset

- CONTRIBUTING.md
- package.json
Bumps package to 5.8.2.
It isn't clear how to release this package and it doesn't seem to have automated version bumping or releasing.
> chore: 5.8.2
